<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title text-danger" id="myModalLabel">Atenção</h4>
            </div>
            <div class="modal-body">
                <p>Ao deletar este registro não será possível recuperá-lo novamente!</p>
                <p>Você tem certeza que deseja deleta-lo?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger conf-delete">Deletar</button>
            </div>
        </div>
    </div>
</div>