<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'partials/breadcrumbs'          => __DIR__ . '/view/partials/breadcrumbs.phtml',
    'partials/flashMessenger'       => __DIR__ . '/view/partials/flashMessenger.phtml',
    'partials/formElementErrors'    => __DIR__ . '/view/partials/formElementErrors.phtml',
    'partials/modal.delete.message' => __DIR__ . '/view/partials/modal.delete.message.phtml',
    'partials/paginator'            => __DIR__ . '/view/partials/paginator.phtml',
);
